menu:
  文档: /docs/
  API: /api/classes/Hexo.html
  新闻: /news/
  插件: https://github.com/tommy351/hexo/wiki/Plugins
  主题: https://github.com/tommy351/hexo/wiki/Themes

doc_sidebar:
  快速开始:
    概述: index.html
    开始: setup.html
    配置: configuration.html
    命令: commands.html
    迁移: migration.html
  基本用法:
    撰写: writing.html
    草稿: drafts.html
    生成: generating.html
    标签插件: tag-plugins.html
    服务器: server.html
    发布: deployment.html
  自定义:
    链接格式: permalinks.html
    主题: themes.html
    变量: variables.html
    分页: pagination.html
    帮助: helpers.html
    插件: plugins.html
  高级:
    模型: models.html
    事件: events.html
  杂项:
    常见问题: troubleshooting.html
    建议: contributing.html

google_analytics: UA-4910098-10
fb_admins: 100000247608790
swiftype_key: DDvzs7LQ9kdKssQNQLcv
twitter: hexojs
github: hexojs/hexo